server:
  port: 8081

mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.limaila.cloud.entitys    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-user
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    #driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://www.limaila.com:3306/cloud?useUnicode=true&characterEncoding=UTF-8             # 数据库名称
    username: hxc
    password: hxc

jetcache:
  areaInCacheName: false
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: www.limaila.com
      port: 6379
      password: hxc
      #sentinels: 127.0.0.1:26379 , 127.0.0.1:26380, 127.0.0.1:26381
      #masterName: mymaster


