spring:
  application:
    name: ci-order-web
  data:
    mongodb:
      uri: mongodb://mongo.limaila.com/ci-order
      port: 27017

dubbo:
  scan:
    base-packages: com.husen.ci
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://zk.limaila.com:2181
    file: ${user.home}/${spring.application.name}-dubbo.cache
  consumer:
    init: false
    check: false



server:
  port: 8082
logging:
  path: ${user.home}/${spring.application.name}
  level:
    root: debug