apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: ci-user-web
  namespace: ci
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: ci-user-web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
