apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ci-user-web
  labels:
    app: ci-user-web
  namespace: ci
spec:
  # 副本数
  replicas: 1
  selector:
    matchLabels:
      app: ci-user-web
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ci-user-web
    spec:
      containers:
      - name: ci-user-web
        image: registry-vpc.cn-shenzhen.aliyuncs.com/huangxincheng/ci-user-web:1.1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        lifecycle:
          preStop:
            exec:
              command:
                - ls /root
        env:
        - name: JAVA_OPTS
          value: "-server -Xmx512m -Xms512m"
        volumeMounts:
        - mountPath: /root/ci-user-web
          name: logs
      volumes:
      - name: logs
        hostPath:
          path: /logs

---

# 正常情况只有网关才需要暴露nodePort。
# 暂时没有网关，故暴露nodePort
apiVersion: v1
kind: Service
metadata:
  name: ci-user-web
  namespace: ci
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30081
  selector:
    app: ci-user-web
