apiVersion: v1
kind: Deployment
metadata:
  name: ci-user-web
  lables:
    app: ci-user-web
  namespace: ci
spec:
  # 副本数
  replicas: 1
  selector:
    matchLables:
      app: ci-user-web
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      lables:
        app: ci-user-web
    spec:
      containers:
        - name: ci-user-web
          images: hxc/ci-user-web:1.0-SNAPSHOT
          lifecycle:
            preStop:
              exec:
                command:
                - ls /home
