node {
   def mvnHome
   stage('打包') { // for display purposes
     echo 'one'
   }
   stage('传输') {
     echo 'two'
   }
   stage('部署') {
     echo 'three'
   }
   stage('测试用例') {
        echo 'three'
   }
   stage('最终结果') {
           echo 'three'
   }
}