import java.util.Date
import java.text.DateFormat
import java.text.SimpleDateFormat

def version() {
    SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
    Calendar lastDate = Calendar.getInstance();
    String date = format.format(lastDate.getTime());
    def now = new Date();
    return "VS-" + date + "-" + now.time;
}


pipeline {
    agent any

    environment {
        // 部署人员名称
        deployUserName = ''
        // Git克隆地址
        cloneGitUrl  = 'https://github.com/huangxincheng/CI'
        // 发布阿里云镜像库版本
        dockerVersion = version()
    }

    tools {
            //工具名称必须在Jenkins 管理Jenkins → 全局工具配置中预配置,配置构建工具,例如：maven,gradle
            maven 'maven'
            jdk 'jdk'
    }

    post {
        // 部署失败
        failure {
            mail to: '249270087@qq.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"
        }
        // 部署成功
        success {
            mail to: '249270087@qq.com',
                             subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                             body: "Something is wrong with ${env.BUILD_URL}"
        }
    }

    stages {
        stage('代码拉取') {
            steps {
                script {
                    deployAppName = params.project
                    cloneGitBranch = params.branch
                    echo "${deployAppName}"
                    echo cloneGitBranch
                    echo params.branch
                    sh "ssh root@47.106.95.198 clone.sh ${cloneGitBranch} ${cloneGitUrl}"
                }
            }
        }
        stage('编译代码生成镜像') {
            steps {
                script {
                    // 远程 k8s-master进行打包
                    sh "ssh root@47.106.95.198 compile.sh"
                }
            }
        }
        stage('上传本地镜像到阿里云仓库') {
            steps {
                script {
                    deployAppName = params.project
                    deployAppVersion = 1.1
                    deployDockerVersion = dockerVersion
                    sh "ssh root@47.106.95.198 uploadLocalDockerImageToAliYun.sh ${deployAppName} ${deployAppVersion} ${deployDockerVersion}"
                }
            }
        }
        stage('K8S部署项目') {
            steps {
                script {
                    deployAppName = params.project
                    deployAppVersion = 1.1
                    sh "ssh root@47.106.95.198 deployAppByAliYunImage.sh ${deployAppName} ${deployDockerVersion}"
                }
            }
        }
    }
}