pipeline {
    agent any

    tools {
            //工具名称必须在Jenkins 管理Jenkins → 全局工具配置中预配置,配置构建工具,例如：maven,gradle
            maven 'maven'
            jdk 'jdk'
    }

    stages {
        stage('打包') {
            steps {
                echo '打包..'
            }
        }
        stage('传输') {
            steps {
                echo '传输..'
            }
        }
        stage('部署') {
            steps {
                echo '部署....'
            }
        }
    }
}