server:
  port: 6001
spring:
  application:
    name: microservicecloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huangxincheng/spring-cloud-config-repo.git
          username: huangxincheng
          password: a6610588