server:
  port: 8079
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
      # 自定义服务名称
      instance-id: ${spring.application.name}:${server.port}
      # 访问路径可以显示IP
      prefer-ip-address: true
spring:
  application:
    name: microservicecloud-comsumer-feign-dept

feign:
  hystrix:
    enabled: true

# 解决第一次请求报超时异常的方案，因为 hystrix 的默认超时时间是 1 秒，因此请求超过该时间后，就会出现页面超时显示 ：
# 这里就介绍大概三种方式来解决超时的问题，解决方案如下：
# 第一种方式：将 hystrix 的超时时间设置成 5000 毫秒
# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
# 或者：
# 第二种方式：将 hystrix 的超时时间直接禁用掉，这样就没有超时的一说了，因为永远也不会超时了
# hystrix.command.default.execution.timeout.enabled: false
# 或者：
# 第三种方式：索性禁用feign的hystrix支持
# feign.hystrix.enabled: false ## 索性禁用feign的hystrix支持
# 超时的issue：https://github.com/spring-cloud/spring-cloud-netflix/issues/768
# 超时的解决方案： http://stackoverflow.com/questions/27375557/hystrix-command-fails-with-timed-out-and-no-fallback-available
# hystrix配置： https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000