server:
  port: 8079
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
      # 自定义服务名称
      instance-id: ${spring.application.name}:${server.port}
      # 访问路径可以显示IP
      prefer-ip-address: true
spring:
  application:
    name: microservicecloud-comsumer-feign-dept
